# Generated by Django 6.0.7 on 2026-08-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donateur', 'Donateur'), ('enseignant', 'Enseignant'), ('responsable', 'Responsable')], max_length=20, verbose_name='rôle'),
        ),
    ]
