# Generated by Django 6.0.7 on 2026-08-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='الاسم العائلي')),
                ('prenom', models.CharField(max_length=100, verbose_name='الاسم الشخصي')),
                ('poste', models.CharField(max_length=100, verbose_name='المنصب')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('date_entree', models.DateField(blank=True, null=True, verbose_name='تاريخ الالتحاق')),
                ('statut', models.CharField(choices=[('actif', 'نشط'), ('inactif', 'غير نشط')], default='actif', max_length=10)),
            ],
        ),
    ]
