# Generated by Django 6.0.7 on 2026-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0002_beneficiaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CIN'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='enfants_scolarises',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nombre_enfants',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='probleme_sante',
            field=models.BooleanField(default=False, verbose_name='Un membre de la famille a un problème de santé'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='consentement_donnees',
            field=models.BooleanField(default=False, verbose_name="J'accepte le traitement de mes données personnelles (loi 09-08)"),
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='type_aide',
            field=models.CharField(choices=[('financiere', 'Financière'), ('en_nature', 'En nature')], default='financiere', max_length=15),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve'), ('orphelin', 'Orphelin'), ('situation_difficile', 'Situation difficile'), ('autre', 'Autre')], max_length=30),
        ),
    ]
