# Generated by Django 6.0.7 on 2026-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0003_beneficiaire_adresse_beneficiaire_cin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeaide',
            name='type_aide',
            field=models.CharField(choices=[('financiere', 'Financière'), ('en_nature', 'En nature')], max_length=15),
        ),
    ]
