# Generated by Django 6.0.7 on 2026-08-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0004_alter_demandeaide_type_aide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaire',
            name='user',
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nom',
            field=models.CharField(default='', max_length=100, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='prenom',
            field=models.CharField(default='', max_length=100, verbose_name='prénom'),
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='numéro de dossier'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='enfants_scolarises',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='enfants scolarisés'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='nombre_enfants',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="nombre d'enfants"),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve'), ('orphelin', 'Orphelin'), ('situation_difficile', 'Situation difficile'), ('autre', 'Autre')], max_length=30, verbose_name='situation familiale'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='demandeaide',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_aide', to='aide.beneficiaire'),
        ),
        migrations.AlterField(
            model_name='demandeaide',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='demandeaide',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='demandeaide',
            name='type_aide',
            field=models.CharField(choices=[('financiere', 'Financière'), ('en_nature', 'En nature')], max_length=15, verbose_name="type d'aide"),
        ),
        migrations.AlterField(
            model_name='demandeaide',
            name='urgence',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], max_length=10, verbose_name='urgence'),
        ),
    ]
