# Generated by Django 6.0.7 on 2026-08-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0005_remove_beneficiaire_user_beneficiaire_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeaide',
            name='type_aide',
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='categorie',
            field=models.CharField(choices=[('etude', 'Étude et scolarité'), ('nutrition', 'Nutrition'), ('sante', 'Santé'), ('couture', 'Matériel de couture')], default='etude', max_length=15, verbose_name='catégorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='montant_demande',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='montant demandé'),
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='titre',
            field=models.CharField(default='', max_length=150, verbose_name='titre de la demande'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('marie', 'Marié(e)'), ('celibataire', 'Célibataire'), ('veuf', 'Veuf/Veuve'), ('divorce', 'Divorcé(e)')], max_length=30, verbose_name='situation familiale'),
        ),
    ]
