# Generated by Django 6.0.7 on 2026-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0006_remove_demandeaide_type_aide_demandeaide_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('marie', 'متزوج(ة)'), ('celibataire', 'أعزب / عزباء'), ('veuf', 'أرمل(ة)'), ('divorce', 'مطلّق(ة)')], max_length=30, verbose_name='situation familiale'),
        ),
        migrations.AlterField(
            model_name='demandeaide',
            name='categorie',
            field=models.CharField(choices=[('etude', 'الدراسة والتمدرس'), ('nutrition', 'التغذية'), ('sante', 'الصحة'), ('couture', 'مواد الخياطة')], max_length=15, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='demandeaide',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'قيد الانتظار'), ('en_cours', 'قيد المعالجة'), ('acceptee', 'مقبولة'), ('refusee', 'مرفوضة')], default='en_attente', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='demandeaide',
            name='urgence',
            field=models.CharField(choices=[('faible', 'عادي'), ('moyenne', 'مستعجل'), ('haute', 'مستعجل جدًا')], max_length=10, verbose_name='urgence'),
        ),
    ]
