# Generated by Django 6.0.7 on 2026-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0007_alter_beneficiaire_situation_familiale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
    ]
