# Generated by Django 6.0.7 on 2026-08-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0007_alter_beneficiaire_situation_familiale_and_more'),
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionformation',
            name='numero_inscription',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='inscriptionformation',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formation', to='aide.beneficiaire'),
        ),
        migrations.AlterField(
            model_name='inscriptionformation',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'قيد التكوين'), ('terminee', 'منتهية'), ('abandonnee', 'متوقفة')], default='en_cours', max_length=20),
        ),
    ]
