# Generated by Django 6.0.7 on 2026-08-03 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_don', models.DateField(auto_now_add=True)),
                ('type_don', models.CharField(choices=[('unique', 'Unique'), ('mensuel', 'Mensuel')], max_length=10)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_affectation', 'En affectation'), ('distribue', 'Distribué')], default='recu', max_length=20)),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_affecte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('cible', models.CharField(choices=[('beneficiaire', 'Bénéficiaire'), ('ecole', 'École'), ('centre_formation', 'Centre de formation')], max_length=20)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='comptabilite.budget')),
                ('don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='dons.don')),
            ],
        ),
    ]
