# Generated by Django 6.0.7 on 2026-08-05 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0003_beneficiaire_adresse_beneficiaire_cin_and_more'),
        ('comptabilite', '0001_initial'),
        ('dons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='demande_aide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='aide.demandeaide'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='validee_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cible', 'beneficiaire'), ('demande_aide__isnull', False)), models.Q(models.Q(('cible', 'beneficiaire'), _negated=True), ('demande_aide__isnull', True)), _connector='OR'), name='affectation_demande_aide_coherente'),
        ),
    ]
