# Generated by Django 6.0.7 on 2026-08-05 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0002_affectation_demande_aide_affectation_validee_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='validee_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
