# Generated by Django 6.0.7 on 2026-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0003_alter_affectation_validee_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='cible',
            field=models.CharField(choices=[('beneficiaire', 'Bénéficiaire'), ('ecole', 'École'), ('centre_formation', 'Centre de formation')], max_length=20, verbose_name='cible'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='montant_affecte',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant affecté'),
        ),
        migrations.AlterField(
            model_name='don',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='don',
            name='statut',
            field=models.CharField(choices=[('recu', 'Reçu'), ('en_affectation', 'En affectation'), ('distribue', 'Distribué')], default='recu', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='don',
            name='type_don',
            field=models.CharField(choices=[('unique', 'Unique'), ('mensuel', 'Mensuel')], max_length=10, verbose_name='type de don'),
        ),
    ]
