# Generated by Django 6.0.7 on 2026-08-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0006_remove_demandeaide_type_aide_demandeaide_categorie_and_more'),
        ('dons', '0004_alter_affectation_cible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='demande_aide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons_cibles', to='aide.demandeaide', verbose_name='cas soutenu'),
        ),
    ]
