# Generated by Django 6.0.7 on 2026-08-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aide', '0007_alter_beneficiaire_situation_familiale_and_more'),
        ('dons', '0005_don_demande_aide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='cible',
            field=models.CharField(choices=[('beneficiaire', 'مستفيد'), ('ecole', 'المدرسة'), ('centre_formation', 'مركز التكوين')], max_length=20, verbose_name='الوجهة'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='montant_affecte',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الموزّع'),
        ),
        migrations.AlterField(
            model_name='don',
            name='demande_aide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons_cibles', to='aide.demandeaide', verbose_name='الحالة المدعومة'),
        ),
        migrations.AlterField(
            model_name='don',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='don',
            name='statut',
            field=models.CharField(choices=[('recu', 'مستلم'), ('en_affectation', 'قيد التوزيع'), ('distribue', 'موزّع')], default='recu', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='don',
            name='type_don',
            field=models.CharField(choices=[('unique', 'لمرة واحدة'), ('mensuel', 'شهري')], max_length=10, verbose_name='نوع التبرّع'),
        ),
    ]
