# Generated by Django 6.0.7 on 2026-09-02 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0006_alter_affectation_cible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='email_invite',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد المتبرّع'),
        ),
        migrations.AddField(
            model_name='don',
            name='nom_invite',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم المتبرّع'),
        ),
        migrations.AlterField(
            model_name='don',
            name='donateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dons', to=settings.AUTH_USER_MODEL),
        ),
    ]
