# Generated by Django 6.0.7 on 2026-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='الشهر')),
                ('programme', models.CharField(choices=[('aide', 'المساعدات الاجتماعية'), ('ecole', 'المدرسة والتعليم الأولي'), ('formation', 'مركز تكوين المرأة'), ('activites', 'الأنشطة والحملات'), ('gestion', 'التسيير والإدارة')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['mois'],
                'constraints': [models.UniqueConstraint(fields=('mois', 'programme'), name='unique_depense_mois_programme')],
            },
        ),
        migrations.CreateModel(
            name='RecetteMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='الشهر')),
                ('source', models.CharField(choices=[('individus', 'تبرعات الأفراد'), ('cooperation', 'التعاون الوطني'), ('indh', 'المبادرة الوطنية للتنمية البشرية'), ('entreprises', 'تبرعات المقاولات'), ('agr', 'أنشطة مدرة للدخل')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['mois'],
                'constraints': [models.UniqueConstraint(fields=('mois', 'source'), name='unique_recette_mois_source')],
            },
        ),
    ]
