# Generated by Django 6.0.7 on 2026-08-03 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere_niveau', models.CharField(max_length=100)),
                ('planning', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_enseignant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('classe', models.CharField(max_length=50)),
                ('tuteur_nom', models.CharField(max_length=100)),
                ('tuteur_contact', models.CharField(max_length=100)),
                ('tuteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to=settings.AUTH_USER_MODEL)),
                ('enseignants', models.ManyToManyField(blank=True, related_name='eleves', to='ecole.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_echeance', models.DateField()),
                ('statut_paiement', models.CharField(choices=[('du', 'Dû'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='du', max_length=20)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_scolarite', to='comptabilite.budget')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ecole.eleve')),
            ],
        ),
    ]
