# Generated by Django 6.0.7 on 2026-08-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreinscriptionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom_enfant', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('prenom_enfant', models.CharField(max_length=100, verbose_name='الاسم الشخصي')),
                ('date_naissance', models.DateField(verbose_name='تاريخ الازدياد')),
                ('tuteur_nom', models.CharField(max_length=100, verbose_name='اسم الولي')),
                ('tuteur_contact', models.CharField(max_length=100, verbose_name='هاتف الولي')),
                ('adresse', models.TextField(blank=True, verbose_name='العنوان')),
                ('statut', models.CharField(choices=[('en_attente', 'قيد الانتظار'), ('acceptee', 'مقبولة'), ('refusee', 'مرفوضة')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
